apiVersion: v1
name: k8tz
description: Kubernetes admission controller to inject timezones into Pods and CronJobs
version: 0.6.0
appVersion: "0.6.0"
icon: https://github.com/k8tz/k8tz/raw/master/assets/k8tz-icon-transparent.png
home: http://k8tz.io
sources:
  - https://github.com/k8tz/k8tz
keywords:
  - timezone
  - timezones
  - admission
  - controller
