{{- if and (ne .Values.kind "DaemonSet") (ne .Values.kind "Deployment") }}
  {{ fail "kind must be Deployment or DaemonSet (case sensitive)" }}
{{- end }}
apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "k8tz.fullname" . }}
  namespace: {{ include "k8tz.namespace" . }}
  labels:
    {{- include "k8tz.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.kind "Deployment" }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8tz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/admission-webhook.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "k8tz.podLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: tls
        secret:
          secretName: {{ include "k8tz.fullname" . }}-tls
      {{- if .Values.webhook.certManager.enabled }}
      - name: shared-tls
        emptyDir: {}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8tz.serviceAccountName" . }}
      securityContext:
        {{- include "k8tz.podSecurityContext" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - "webhook"
          - "--timezone"
          - {{ .Values.timezone | quote }}
          - "--injection-strategy"
          - {{ .Values.injectionStrategy | quote }}
          - "--inject={{ .Values.injectAll }}"
          - "--container-name={{ .Values.injectedInitContainerName }}"
          - "--bootstrap-image"
          - "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.verbose }}
          - "--verbose"
          - "--bootstrap-verbose"
          {{- end }}
          {{- if .Values.webhook.certManager.enabled }}
          - "--tls-crt"
          - "/run/secrets/shared-tls/tls.crt"
          - "--tls-key"
          - "/run/secrets/shared-tls/tls.key"
          {{- end }}
          {{- if .Values.cronJobTimeZone }}
          {{- if and (ge .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "24") }}
          - "--cronJobTimeZone"
          {{- else }}
          {{- fail "CronJob injection requires kubernetes >=1.24.0-beta.0 with 'CronJobTimeZone' feature gate enabled" }}
          {{- end }}
          {{- end }}
          {{- if .Values.webhook.tlsMinVersion }}
          - "--tls-min-version"
          - "{{ .Values.webhook.tlsMinVersion }}"
          {{- end }}
          {{- if .Values.webhook.tlsCipherSuites }}
          - "--tls-cipher-suites"
          - "{{ .Values.webhook.tlsCipherSuites }}"
          {{- end }}
          {{- if .Values.initContainerResources }}
          - "--bootstrap-resources"
          - {{ .Values.initContainerResources | toJson | quote }}
          {{- end}}
          securityContext:
            {{- include "k8tz.securityContext" . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tls
              mountPath: /run/secrets/tls
              readOnly: true
            {{- if .Values.webhook.certManager.enabled }}
            - name: shared-tls
              mountPath: /run/secrets/shared-tls
              readOnly: true
            {{- end }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.webhook.certManager.enabled }}
        - name: {{ .Chart.Name }}-cert-watcher
          args:
          - "cert-watcher"
          - "--tls-crt"
          - "/run/secrets/shared-tls/tls.crt"
          - "--tls-key"
          - "/run/secrets/shared-tls/tls.key"
          - "--secret-name"
          - {{ include "k8tz.fullname" . }}-tls
          - "--secret-namespace"
          - {{ include "k8tz.namespace" . }}
          securityContext:
            {{- include "k8tz.securityContext" . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tls
              mountPath: /run/secrets/tls
              readOnly: true
            - name: shared-tls
              mountPath: /run/secrets/shared-tls
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
